title: ServoDevelop Wiki

remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true

# GitHub Pages project site under /wiki
url: "https://servodevelop.github.io"
baseurl: "/wiki"
