site_name: Fashion Star Wiki
site_url: https://wiki.fashionstar.com.hk/
use_directory_urls: true

theme:
  name: material
#  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: false
  favicon: assets/favicon.png
  custom_dir: docs/overrides 

  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - toc.follow
    - content.tabs.link
    - navigation.tabs
    - i18n.languages

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: fashion/tech-moon
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: fashion/tech-sun
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.tilde

hooks:
  - docs/hooks/gh_alerts.py

plugins:
- search:
      # åªéœ€è¦ enã€‚å› ä¸º jieba ä¼šè‡ªåŠ¨å¤„ç†æ‰€æœ‰éæ‹‰ä¸å­—ç¬¦ï¼ˆä¸­æ–‡ï¼‰
      lang: en
      # å¿…é¡»ä¿ç•™è¿™ä¸ªï¼Œå¦åˆ™ jieba åˆ†å‡ºæ¥çš„è¯åœ¨å‰ç«¯æœä¸åˆ°
      separator: '[\s\u200b\-]'
  - glightbox
  - include-markdown:
      rewrite_relative_urls: true
      dedent: true
  - i18n:
      default_locale: en
      reconfigure_material: true
      fallback_to_default: true 
      # ã€æœ€å…³é”®ï¼šå®ç°ä½ çš„éš”ç¦»éœ€æ±‚ã€‘
      indexing: 'separate'
      languages:
        # è‹±æ–‡é»˜è®¤é…ç½®
        - locale: en
          name: "ğŸ‡ºğŸ‡¸ English"
          default: true
          build: true
        # ä¸­æ–‡é…ç½®ï¼šç›´æ¥åœ¨è¿™é‡Œè¦†ç›–æ•´ä¸ª Nav ç»“æ„
        - locale: zh
          name: "ğŸ‡¨ğŸ‡³ ä¸­æ–‡"
          default: false
          build: true
          nav:
            - é¦–é¡µ: index.md
            - UARTæ€»çº¿èˆµæœº:
              - uart_servo/index.md
              - é€šè®¯åè®®: uart_servo/protocols/uart_rs485_protocol.md
              - è§„æ ¼å‚æ•°:
                - RP6-U12H-M: uart_servo/specs/rp6-u12h-m.md
                - RX6-U12H-M: uart_servo/specs/rx6-u12h-m.md
                - HP6/RP6-U15H-M: uart_servo/specs/hp-rp6-u15h-m.md
                - RP6-U18H-M: uart_servo/specs/rp6-u18h-m.md
                - HA8/RA8-U25(H)-M: uart_servo/specs/ha-ra8-u25h-m.md
                - HX8/RX8-U28H-M: uart_servo/specs/hx-rx8-u28h-m.md
                - HX8/RX8-U29H-M: uart_servo/specs/hx-rx8-u29h-m.md
                - HA8/RA8-U35(H)-M: uart_servo/specs/ha-ra8-u35h-m.md
                - HA8/RA8-U45(H)-M: uart_servo/specs/ha-ra8-u45h-m.md
                - HX8/RX8-U50H-M: uart_servo/specs/hx-rx8-u50h-m.md
                - HX8/RX8-U51H-M: uart_servo/specs/hx-rx8-u51h-m.md
                - RX18-U100H-M: uart_servo/specs/rx18-u100h-m.md
                - RX18-U101H-M: uart_servo/specs/rx18-u101h-m.md
              - CADæ–‡ä»¶:
                - RA8/RP8/RX8 ç³»åˆ—: uart_servo/cad_files/ra8-rp8-rx8-series.md
                - RP6/RX6-U12 ç³»åˆ—: uart_servo/cad_files/rp6-rx6-u12-series.md
                - RX6-U15 ç³»åˆ—: uart_servo/cad_files/rx6-u15-series.md
                - RP6-U18 ç³»åˆ—: uart_servo/cad_files/rp6-u18-series.md
                - RX18 ç³»åˆ—: uart_servo/cad_files/rx18-series.md
              - é…å¥—è½¯ä»¶:
                - PCç«¯è°ƒè¯•è½¯ä»¶: uart_servo/software/pc_configuration_tool.md
                - ç½‘é¡µç‰ˆè°ƒè¯•å·¥å…·: uart_servo/software/web_configuration_tool.md
              - å¼€å‘åº“:
                - å·¥ä¸šPLC: 
                  - Sinamics: uart_servo/sdk/plc/sinamics_tia_portal_v19.md
                  - Codesys: uart_servo/sdk/plc/codesys.md
                  - Inovance: uart_servo/sdk/plc/inovance.md
                  - Inoproshop: uart_servo/sdk/plc/inovance_inoproshop.md
                  - GX Works: uart_servo/sdk/plc/mitsubishi_gx_works2.md
                  - Step7 MicroWin: uart_servo/sdk/plc/step7_microwin_smart.md
                - Stm32f103: uart_servo/sdk/stm32f103_sdk.md
                - Stm32f407: uart_servo/sdk/stm32f407_sdk.md
                - Arduino: uart_servo/sdk/arduino_sdk.md
                - Python: uart_servo/sdk/python_sdk.md
                - Micro Python: uart_servo/sdk/micropython_sdk.md
                - C++: "uart_servo/sdk/cpp_sdk.md"
                - "C#": "uart_servo/sdk/csharp_sdk.md"
                - Ros: uart_servo/sdk/ros_sdk.md
              - å®˜æ–¹æ–‡æ¡£: uart_servo/documents/uc01_instruction_manual.md
            - RS485æ€»çº¿èˆµæœº:
              - rs485_servo/index.md
              - é€šè®¯åè®®: rs485_servo/protocols/uart_rs485_protocol.md
              - è§„æ ¼å‚æ•°:
                - HX8-R28H-M: rs485_servo/specs/hx8-r28h-m.md
                - HX8-R29H-M: rs485_servo/specs/hx8-r29h-m.md
                - HX8-R50H-M: rs485_servo/specs/hx8-r50h-m.md
                - HX8-R51H-M: rs485_servo/specs/hx8-r51h-m.md
                - RX18-R100H-M: rs485_servo/specs/rx18-r100h-m.md
                - RX18-R101H-M: rs485_servo/specs/rx18-r101h-m.md
              - CADæ–‡ä»¶:
                - HX8/RX8 R ç³»åˆ—: rs485_servo/cad_files/hx8-rx8-r-series.md
                - HX18 R ç³»åˆ—: rs485_servo/cad_files/hx18-r-series.md
              - é…å¥—è½¯ä»¶:
                - PCç«¯è°ƒè¯•è½¯ä»¶: rs485_servo/software/pc_configuration_tool.md
                - ç½‘é¡µç‰ˆè°ƒè¯•å·¥å…·: rs485_servo/software/web_configuration_tool.md
              - å¼€å‘åº“:
                - å·¥ä¸šPLC:
                  - Sinamics: rs485_servo/sdk/plc/sinamics_tia_portal_v19.md
                  - Codesys: rs485_servo/sdk/plc/codesys.md
                  - Inovance: rs485_servo/sdk/plc/inovance.md
                  - Inoproshop: rs485_servo/sdk/plc/inovance_inoproshop.md
                  - GX Works: rs485_servo/sdk/plc/mitsubishi_gx_works2.md
                  - Step7 MicroWin: rs485_servo/sdk/plc/step7_microwin_smart.md
                - Stm32f103: rs485_servo/sdk/stm32f103_sdk.md
                - Stm32f407: rs485_servo/sdk/stm32f407_sdk.md
                - Arduino: rs485_servo/sdk/arduino_sdk.md
                - Python: rs485_servo/sdk/python_sdk.md
                - Micro Python: rs485_servo/sdk/micropython_sdk.md
                - C++: rs485_servo/sdk/cpp_sdk.md
                - "C#": rs485_servo/sdk/csharp_sdk.md
                - Ros: rs485_servo/sdk/ros_sdk.md
              - å®˜æ–¹æ–‡æ¡£: rs485_servo/documents/uc01_instruction_manual.md
            - CANæ€»çº¿èˆµæœº:
              - é€šè®¯åè®®: can_servo/protocols/can_protocol.md
              - è§„æ ¼å‚æ•°:
                - HX8-C100H-M: can_servo/specs/hx8-c100h-m.md
                - HX8-C100W-M: can_servo/specs/hx8-c100w-m.md
              - CADæ–‡ä»¶:
                - HX8/RX8 C ç³»åˆ—: can_servo/cad_files/hx8-rx8-c-series.md
                - HX18 C ç³»åˆ—: can_servo/cad_files/hx18-c-series.md
              - é…å¥—è½¯ä»¶:
                - PCç«¯è°ƒè¯•è½¯ä»¶: can_servo/software/pc_configuration_tool.md
                - ç½‘é¡µç‰ˆè°ƒè¯•å·¥å…·: can_servo/software/web_configuration_tool.md
              - å¼€å‘åº“:
                - å·¥ä¸šPLC:
                  - Sinamics: can_servo/sdk/plc/sinamics_tia_portal_v19.md
                  - Codesys: can_servo/sdk/plc/codesys.md
                  - Inovance: can_servo/sdk/plc/inovance.md
                  - Inoproshop: can_servo/sdk/plc/inovance_inoproshop.md
                  - GX Works: can_servo/sdk/plc/mitsubishi_gx_works2.md
                  - Step7 MicroWin: can_servo/sdk/plc/step7_microwin_smart.md
                - Stm32f103: can_servo/sdk/stm32f103_sdk.md
                - Stm32f407: can_servo/sdk/stm32f407_sdk.md
                - Arduino: can_servo/sdk/arduino_sdk.md
                - Python: can_servo/sdk/python_sdk.md
                - Micro Python: can_servo/sdk/micropython_sdk.md
                - C++: can_servo/sdk/cpp_sdk.md
                - "C#": can_servo/sdk/csharp_sdk.md
                - Ros: can_servo/sdk/ros_sdk.md
              - å®˜æ–¹æ–‡æ¡£: can_servo/documents/uc01_instruction_manual.md
            - æœºæ¢°è‡‚:
              - StarAIæœºæ¢°è‡‚:
                - å¿«é€Ÿå…¥é—¨: robotic_arm/starai_arm/quick_start.md
              - Piper Mate:
                - å‡†å¤‡å·¥ä½œ: robotic_arm/piper_mate/get_ready.md

# æ ¹å¯¼èˆªå®šä¹‰ï¼ˆä¸»è¦ç”¨äºé»˜è®¤è¯­è¨€ï¼Œå³è‹±æ–‡ï¼‰
nav:
  - Home: index.md
  - Uart Bus Servo:
    - uart_servo/index.md
    - Protocol: uart_servo/protocols/uart_rs485_protocol.md
    - Specifications:
      - RP6-U12H-M: uart_servo/specs/rp6-u12h-m.md
      - RX6-U12H-M: uart_servo/specs/rx6-u12h-m.md
      - HP6/RP6-U15H-M: uart_servo/specs/hp-rp6-u15h-m.md
      - RP6-U18H-M: uart_servo/specs/rp6-u18h-m.md
      - HA8/RA8-U25(H)-M: uart_servo/specs/ha-ra8-u25h-m.md
      - HX8/RX8-U28H-M: uart_servo/specs/hx-rx8-u28h-m.md
      - HX8/RX8-U29H-M: uart_servo/specs/hx-rx8-u29h-m.md
      - HA8/RA8-U35(H)-M: uart_servo/specs/ha-ra8-u35h-m.md
      - HA8/RA8-U45(H)-M: uart_servo/specs/ha-ra8-u45h-m.md
      - HX8/RX8-U50H-M: uart_servo/specs/hx-rx8-u50h-m.md
      - HX8/RX8-U51H-M: uart_servo/specs/hx-rx8-u51h-m.md
      - RX18-U100H-M: uart_servo/specs/rx18-u100h-m.md
      - RX18-U101H-M: uart_servo/specs/rx18-u101h-m.md
    - CAD Files:
      - RA8/RP8/RX8 Series: uart_servo/cad_files/ra8-rp8-rx8-series.md
      - RP6/RX6-U12 Series: uart_servo/cad_files/rp6-rx6-u12-series.md
      - RX6-U15 Series: uart_servo/cad_files/rx6-u15-series.md
      - RP6-U18 Series: uart_servo/cad_files/rp6-u18-series.md
      - RX18 Series: uart_servo/cad_files/rx18-series.md
    - Software:
      - PC Configuration Tool: uart_servo/software/pc_configuration_tool.md
      - Web Configuration Tool: uart_servo/software/web_configuration_tool.md
    - SDK:
      - PLC: 
        - Sinamics: uart_servo/sdk/plc/sinamics_tia_portal_v19.md
        - Codesys: uart_servo/sdk/plc/codesys.md
        - Inovance: uart_servo/sdk/plc/inovance.md
        - Inoproshop: uart_servo/sdk/plc/inovance_inoproshop.md
        - GX Works: uart_servo/sdk/plc/mitsubishi_gx_works2.md
        - Step7 MicroWin: uart_servo/sdk/plc/step7_microwin_smart.md
      - Stm32f103: uart_servo/sdk/stm32f103_sdk.md
      - Stm32f407: uart_servo/sdk/stm32f407_sdk.md
      - Arduino: uart_servo/sdk/arduino_sdk.md
      - Python: uart_servo/sdk/python_sdk.md
      - Micro Python: uart_servo/sdk/micropython_sdk.md
      - C++: "uart_servo/sdk/cpp_sdk.md"
      - "C#": "uart_servo/sdk/csharp_sdk.md"
      - Ros: uart_servo/sdk/ros_sdk.md
    - Document: uart_servo/documents/uc01_instruction_manual.md
  - RS485 Bus Servo:
    - rs485_servo/index.md
    - Protocol: rs485_servo/protocols/uart_rs485_protocol.md
    - Specifications:
      - HX8-R28H-M: rs485_servo/specs/hx8-r28h-m.md
      - HX8-R29H-M: rs485_servo/specs/hx8-r29h-m.md
      - HX8-R50H-M: rs485_servo/specs/hx8-r50h-m.md
      - HX8-R51H-M: rs485_servo/specs/hx8-r51h-m.md
      - RX18-R100H-M: rs485_servo/specs/rx18-r100h-m.md
      - RX18-R101H-M: rs485_servo/specs/rx18-r101h-m.md
    - CAD Files:
      - HX8/RX8 R Series: rs485_servo/cad_files/hx8-rx8-r-series.md
      - HX18 R Series: rs485_servo/cad_files/hx18-r-series.md
    - Software:
      - PC Configuration Tool: rs485_servo/software/pc_configuration_tool.md
      - Web Configuration Tool: rs485_servo/software/web_configuration_tool.md
    - SDK:
      - PLC:
        - Sinamics: rs485_servo/sdk/plc/sinamics_tia_portal_v19.md
        - Codesys: rs485_servo/sdk/plc/codesys.md
        - Inovance: rs485_servo/sdk/plc/inovance.md
        - Inoproshop: rs485_servo/sdk/plc/inovance_inoproshop.md
        - GX Works: rs485_servo/sdk/plc/mitsubishi_gx_works2.md
        - Step7 MicroWin: rs485_servo/sdk/plc/step7_microwin_smart.md
      - Stm32f103: rs485_servo/sdk/stm32f103_sdk.md
      - Stm32f407: rs485_servo/sdk/stm32f407_sdk.md
      - Arduino: rs485_servo/sdk/arduino_sdk.md
      - Python: rs485_servo/sdk/python_sdk.md
      - Micro Python: rs485_servo/sdk/micropython_sdk.md
      - C++: rs485_servo/sdk/cpp_sdk.md
      - "C#": rs485_servo/sdk/csharp_sdk.md
      - Ros: rs485_servo/sdk/ros_sdk.md
    - Document: rs485_servo/documents/uc01_instruction_manual.md
  - CAN Bus Servo:
    - Protocol: can_servo/protocols/can_protocol.md
    - Specifications:
      - HX8-C100H-M: can_servo/specs/hx8-c100h-m.md
      - HX8-C100W-M: can_servo/specs/hx8-c100w-m.md
    - CAD Files:
      - HX8/RX8 C Series: can_servo/cad_files/hx8-rx8-c-series.md
      - HX18 C Series: can_servo/cad_files/hx18-c-series.md
    - Software:
      - PC Configuration Tool: can_servo/software/pc_configuration_tool.md
      - Web Configuration Tool: can_servo/software/web_configuration_tool.md
    - SDK:
      - PLC:
        - Sinamics: can_servo/sdk/plc/sinamics_tia_portal_v19.md
        - Codesys: can_servo/sdk/plc/codesys.md
        - Inovance: can_servo/sdk/plc/inovance.md
        - Inoproshop: can_servo/sdk/plc/inovance_inoproshop.md
        - GX Works: can_servo/sdk/plc/mitsubishi_gx_works2.md
        - Step7 MicroWin: can_servo/sdk/plc/step7_microwin_smart.md
      - Stm32f103: can_servo/sdk/stm32f103_sdk.md
      - Stm32f407: can_servo/sdk/stm32f407_sdk.md
      - Arduino: can_servo/sdk/arduino_sdk.md
      - Python: can_servo/sdk/python_sdk.md
      - Micro Python: can_servo/sdk/micropython_sdk.md
      - C++: can_servo/sdk/cpp_sdk.md
      - "C#": can_servo/sdk/csharp_sdk.md
      - Ros: can_servo/sdk/ros_sdk.md
    - Document: can_servo/documents/uc01_instruction_manual.md
  - Robotic Arm:
    - StarAI Arm:
      - Quick Start: robotic_arm/starai_arm/quick_start.md
    - Piper Mate:
      - Get Ready: robotic_arm/piper_mate/get_ready.md
