site_name: Fashion Star Wiki
site_url: https://servodevelop.github.io/wiki/

theme:
  name: material
  language: en

  # Theme overrides directory (keep it under /docs so Actions sparse-checkout won't miss it)
  custom_dir: docs/overrides

  features:
    - navigation.path        # breadcrumb
    - navigation.indexes     # parent index pages clickable
    - navigation.top         # back-to-top
    - navigation.tracking    # sync URL hash
    - content.code.copy      # copy code button
    - toc.follow             # right TOC follows scroll

  palette:
    # light
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        # uses docs/overrides/.icons/fashion/tech-moon.svg
        icon: fashion/tech-moon
        name: Switch to dark mode

    # dark
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        # uses docs/overrides/.icons/fashion/tech-sun.svg
        icon: fashion/tech-sun
        name: Switch to light mode

extra:
  translations:
    en:
      toc.title: "On this page"

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - glightbox

nav:
  - Home: index.md
  - UART Servo:
      - Datasheet:
          - HA8/RA8-U25(H)-M: uart_servo/datasheet/HA_RA8_U25(H)_M.md
          - HA8/RA8-U35(H)-M: uart_servo/datasheet/HA_RA8_U35(H)_M.md
      - CAD Files:
          - STEP/DWG/PDF: uart_servo/cad_files/cad_files.md
      - Software:
          - Configuration Tools: uart_servo/software/pc_configuration_ser_manual.md
  - Robotic Arm:
      - StarAI Arm:
          - Quick Start: robotic_arm/starai_arm/index.md
      - Piper Mate:
          - User Manual: robotic_arm/piper_mate/index.md
