site_name: Fashion Star Wiki
site_url: https://servodevelop.github.io/wiki/

theme:
  name: material
  language: en
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - toc.follow
    - navigation.tabs
    - navigation.sections

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 本次新增修改：覆盖默认的目录标题
extra:
  translations:
    en:
      toc.title: "On this page"

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - UART Servo:
      - Datasheet:
          - HA8/RA8-U25(H)-M: uart_servo/datasheet/HA_RA8_U25(H)_M.md
          - HA8/RA8-U35(H)-M: uart_servo/datasheet/HA_RA8_U35(H)_M.md
      - CAD Files:
          - STEP/DWG/PDF: uart_servo/cad_files/cad_files.md
      - Software: 
          - Configuration Tools: uart_servo/software/pc_configuration_ser_manual.md
  - Robotic Arm:
      - StarAI Arm: 
          - Quick Start: robotic_arm/starai_arm/index.md
      - Piper Mate: 
          - User Manual: robotic_arm/piper_mate/index.md

plugins:
  - search
  - glightbox
