site_name: Fashion Star Wiki
site_url: https://wiki.fashionstar.com.hk/
use_directory_urls: true


theme:
  name: material
  # language: enï¼ˆæ³¨é‡Šæ‰ä¸ºäº†On this Pageå¯ä»¥è·Ÿç€è¯­ç³»è°ƒæ•´æ˜¾ç¤ºï¼‰
  favicon: assets/favicon.png

  # Theme overrides directory (keep it under /docs so Actions sparse-checkout won't miss it)
  custom_dir: docs/overrides

  features:
    - navigation.path        # breadcrumb
    - navigation.indexes     # parent index pages clickable
    - navigation.top         # back-to-top
    - navigation.tracking    # sync URL hash
    - content.code.copy      # copy code button
    - toc.follow             # right TOC follows scroll
    - content.tabs.link    # è”åŠ¨ Tab æ ‡ç­¾é¡µ
    # - content.action.edit  # é¡µé¢å³ä¸Šè§’æ˜¾ç¤ºâ€œç¼–è¾‘æ­¤é¡µâ€å›¾æ ‡
    - navigation.expand    # è‡ªåŠ¨å±•å¼€å·¦ä¾§èœå•

  palette:
    # dark
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        # uses docs/overrides/.icons/fashion/tech-sun.svg
        icon: fashion/tech-sun
        name: Switch to light mode

    # light
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        # uses docs/overrides/.icons/fashion/tech-moon.svg
        icon: fashion/tech-moon
        name: Switch to dark mode

extra:
  translations:
    en:
      toc.title: "On this page"
    es:
      toc.title: "En esta pÃ¡gina"
    fr:
      toc.title: "Sur cette page"
    de:
      toc.title: "Auf dieser Seite"
    ja:
      toc.title: "ã“ã®ãƒšãƒ¼ã‚¸ã®å†…å®¹"


extra_css:
  - stylesheets/extra.css

  # å°† sitemap ç§»å‡º plugins åˆ—è¡¨ï¼Œæ”¾åœ¨è¿™é‡Œä½œä¸º extra é…ç½®ï¼ˆéƒ¨åˆ†ç‰ˆæœ¬æ”¯æŒè¿™æ ·é™çº§å¤„ç†ï¼‰
extra:
  sitemap:
    filename: sitemap.xml

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

hooks:
  - docs/hooks/gh_alerts.py

plugins:
  - search
  - glightbox
  - include-markdown:
      rewrite_relative_urls: true
      dedent: true
  - i18n:
      default_language: en
      reconfigure_material: true
      # å¼€å¯æ­¤é¡¹å¯ä»¥è®© SEO çˆ¬è™«åœ¨ä¸åŒè¯­è¨€é—´æ— ç¼åˆ‡æ¢ï¼Œå¹¶è‡ªåŠ¨å¼•å¯¼ç”¨æˆ·åˆ°é¦–é€‰è¯­è¨€
      link_to_preferred_support: true 
      languages:
        # 1. è‹±è¯­ (é»˜è®¤)
        - locale: en
          name: "ğŸ‡ºğŸ‡¸ English"
          default: true
          build: true
        # 2. è¥¿ç­ç‰™è¯­
        - locale: es
          name: "ğŸ‡ªğŸ‡¸ EspaÃ±ol"
          default: false
          build: true
        # 3. æ³•è¯­
        - locale: fr
          name: "ğŸ‡«ğŸ‡· FranÃ§ais"
          default: false
          build: true
        # 4. å¾·è¯­
        - locale: de
          name: "ğŸ‡©ğŸ‡ª Deutsch"
          default: false
          build: true
        # 5. æ—¥è¯­
        - locale: ja
          name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"
          default: false
          build: true



nav:
  - Home: index.md
  - Uart Bus Servo:
      - Protocol: uart_servo/protocols/uart_rs485_protocol.md
      - Specifications:
          - RP6-U12H-M: uart_servo/specs/rp6-u12h-m.md
          - RX6-U12H-M: uart_servo/specs/rx6-u12h-m.md
          - HP6/RP6-U15H-M: uart_servo/specs/hp-rp6-u15h-m.md
          - RP6-U18H-M: uart_servo/specs/rp6-u18h-m.md
          - HA8/RA8-U25(H)-M: uart_servo/specs/ha-ra8-u25h-m.md
          - HX8/RX8-U28H-M: uart_servo/specs/hx-rx8-u28h-m.md
          - HX8/RX8-U29H-M: uart_servo/specs/hx-rx8-u29h-m.md
          - HA8/RA8-U35(H)-M: uart_servo/specs/ha-ra8-u35h-m.md
          - HA8/RA8-U45(H)-M: uart_servo/specs/ha-ra8-u45h-m.md
          - HX8/RX8-U50H-M: uart_servo/specs/hx-rx8-u50h-m.md
          - HX8/RX8-U51H-M: uart_servo/specs/hx-rx8-u51h-m.md
          - RX18-U100H-M: uart_servo/specs/rx18-u100h-m.md
          - RX18-U101H-M: uart_servo/specs/rx18-u101h-m.md
      - CAD Files:
          - RA8/RP8/RX8 Series: uart_servo/cad_files/ra8-rp8-rx8-series.md
          - RP6/RX6-U12 Series: uart_servo/cad_files/rp6-rx6-u12-series.md
          - RX6-U15 Series: uart_servo/cad_files/rx6-u15-series.md
          - RP6-U18 Series: uart_servo/cad_files/rp6-u18-series.md
          - RX18 Series: uart_servo/cad_files/rx18-series.md
      - Software:
          - PC Configuration Tool: uart_servo/software/pc_configuration_tool.md
          - Web Configuration Tool: uart_servo/software/web_configuration_tool.md
      - SDK:
          - PLC: 
              - Sinamics: uart_servo/sdk/plc/sinamics_tia_portal_v19.md
              - Codesys: uart_servo/sdk/plc/codesys.md
              - Inovance: uart_servo/sdk/plc/inovance.md
              - Inoproshop: uart_servo/sdk/plc/inovance_inoproshop.md
              - GX Works: uart_servo/sdk/plc/mitsubishi_gx_works2.md
              - Step7 MicroWin: uart_servo/sdk/plc/step7_microwin_smart.md
          - Stm32f103: uart_servo/sdk/stm32f103_sdk.md
          - Stm32f407: uart_servo/sdk/stm32f407_sdk.md
          - Arduino: uart_servo/sdk/arduino_sdk.md
          - Python: uart_servo/sdk/python_sdk.md
          - Micro Python: uart_servo/sdk/micropython_sdk.md
          - C++: "uart_servo/sdk/cpp_sdk.md"
          - "C#": "uart_servo/sdk/csharp_sdk.md"
          - Ros: uart_servo/sdk/ros_sdk.md
      - Document: uart_servo/documents/uc01_instruction_manual.md
  - RS485 Bus Servo:
    - Protocol: rs485_servo/protocols/uart_rs485_protocol.md
    - Specifications:
        - HX8-R28H-M: rs485_servo/specs/hx8-r28h-m.md
        - HX8-R29H-M: rs485_servo/specs/hx8-r29h-m.md
        - HX8-R50H-M: rs485_servo/specs/hx8-r50h-m.md
        - HX8-R51H-M: rs485_servo/specs/hx8-r51h-m.md
        - RX18-R100H-M: rs485_servo/specs/rx18-r100h-m.md
        - RX18-R101H-M: rs485_servo/specs/rx18-r101h-m.md
    - CAD Files:
        - HX8/RX8 R Series: rs485_servo/cad_files/hx8-rx8-r-series.md
        - HX18 R Series: rs485_servo/cad_files/hx18-r-series.md
    - Software:
        - PC Configuration Tool: rs485_servo/software/pc_configuration_tool.md
        - Web Configuration Tool: rs485_servo/software/web_configuration_tool.md
    - SDK:
        - PLC:
            - Sinamics: rs485_servo/sdk/plc/sinamics_tia_portal_v19.md
            - Codesys: rs485_servo/sdk/plc/codesys.md
            - Inovance: rs485_servo/sdk/plc/inovance.md
            - Inoproshop: rs485_servo/sdk/plc/inovance_inoproshop.md
            - GX Works: rs485_servo/sdk/plc/mitsubishi_gx_works2.md
            - Step7 MicroWin: rs485_servo/sdk/plc/step7_microwin_smart.md
        - Stm32f103: rs485_servo/sdk/stm32f103_sdk.md
        - Stm32f407: rs485_servo/sdk/stm32f407_sdk.md
        - Arduino: rs485_servo/sdk/arduino_sdk.md
        - Python: rs485_servo/sdk/python_sdk.md
        - Micro Python: rs485_servo/sdk/micropython_sdk.md
        - C++: rs485_servo/sdk/cpp_sdk.md
        - "C#": rs485_servo/sdk/csharp_sdk.md
        - Ros: rs485_servo/sdk/ros_sdk.md
    - Document: rs485_servo/documents/uc01_instruction_manual.md
  - CAN Bus Servo:
    - Protocol: can_servo/protocols/can_protocol.md
    - Specifications:
        - HX8-C100H-M: can_servo/specs/hx8-c100h-m.md
        - HX8-C100W-M: can_servo/specs/hx8-c100w-m.md
    - CAD Files:
        - HX8/RX8 C Series: can_servo/cad_files/hx8-rx8-c-series.md
        - HX18 C Series: can_servo/cad_files/hx18-c-series.md
    - Software:
        - PC Configuration Tool: can_servo/software/pc_configuration_tool.md
        - Web Configuration Tool: can_servo/software/web_configuration_tool.md
    - SDK:
        - PLC:
            - Sinamics: can_servo/sdk/plc/sinamics_tia_portal_v19.md
            - Codesys: can_servo/sdk/plc/codesys.md
            - Inovance: can_servo/sdk/plc/inovance.md
            - Inoproshop: can_servo/sdk/plc/inovance_inoproshop.md
            - GX Works: can_servo/sdk/plc/mitsubishi_gx_works2.md
            - Step7 MicroWin: can_servo/sdk/plc/step7_microwin_smart.md
        - Stm32f103: can_servo/sdk/stm32f103_sdk.md
        - Stm32f407: can_servo/sdk/stm32f407_sdk.md
        - Arduino: can_servo/sdk/arduino_sdk.md
        - Python: can_servo/sdk/python_sdk.md
        - Micro Python: can_servo/sdk/micropython_sdk.md
        - C++: can_servo/sdk/cpp_sdk.md
        - "C#": can_servo/sdk/csharp_sdk.md
        - Ros: can_servo/sdk/ros_sdk.md
    - Document: can_servo/documents/uc01_instruction_manual.md
  - Robotic Arm:
      - StarAI Arm:
          - Quick Start: robotic_arm/starai_arm/quick_start.md
      - Piper Mate:
          - Get Ready: robotic_arm/piper_mate/get_ready.md
