site_name: Fashion Star Wiki
site_url: https://servodevelop.github.io/wiki/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs          # 开启顶部一级导航
    - navigation.sections      # 开启侧边栏分组
    - content.code.copy        # 代码一键复制
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

markdown_extensions:
  - pymdownx.snippets:         # 开启嵌套调用功能
      base_path: ["docs"]
  - admonition                 # 开启彩色提示框
  - pymdownx.details           # 开启折叠块
  - pymdownx.superfences       # 开启代码高亮
  - attr_list      # 必须：开启此项才能使用 {: width="45%"} 调整大小
  - md_in_html     # 建议：允许在 HTML 容器内写 Markdown（用于网格布局）

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - UART Servo:
      - Datasheet:
          - HA8/RA8-U25(H)-M: uart_servo/datasheet/HA&RA8-U25(H)-M.md
          - HA8/RA8-U35(H)-M: uart_servo/datasheet/HA&RA8-U35(H)-M.md
